<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "mesas".
 *
 * @property int $id
 * @property int $lotacao
 * @property string $forma
 *
 * @property Mesasmarcacoes[] $mesasmarcacoes
 */
class Mesas extends \yii\db\ActiveRecord
{
    public $mesaredonda = '';
    public $mesaquadrada = '';
    public $mesaretangular = '';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mesas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['lotacao', 'forma'], 'required'],
            [['lotacao'], 'integer'],
            [['forma'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Nº da Mesa',
            'lotacao' => 'Lotação',
            'forma' => 'Forma',
        ];
    }

    /**
     * Gets query for [[Mesasmarcacoes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMesasmarcacoes()
    {
        return $this->hasMany(Mesasmarcacoes::class, ['idMesa' => 'id']);
    }

    public function beforeValidate()
    {
        return parent::beforeValidate(); // TODO: Change the autogenerated stub

    }
}
